apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: geekbozu
        # The Github repository
        repo: argocd-example-apps
  requeueAfterSeconds: 15
  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/geekbozu/argocd-example-apps.git'
        targetRevision: '{{head_sha}}'
        path: Test/
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default